version: "3"

services:

  rest-api:
    extends:
      file: ./rest-api/docker-compose.yml
      service: rest-api
    networks:
      - default
    depends_on:
      - flyway

  postgres:
    extends:
      file: ./database/docker-compose.yml
      service: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  flyway:
    extends:
      file: ./database/docker-compose.yml
      service: flyway
    networks:
      - default
    depends_on:
      - postgres

volumes:
  postgres-data: